### ISSUE TITLE
Upgrade contracts to ink! 4.0

### ISSUE THREAD

**Issue by HCastano** [interlock-network/interlock-smartcontracts#224]
Hi there!

Not sure how closely you follow our release cycle, but we released [ink! 4.0](https://github.com/paritytech/ink/releases/tag/v4.0.0) recently and it would probably be worth your time to update. We wrote a [migration guide](https://use.ink/faq/migrating-from-ink-3-to-4) to help out.

**Comment by blairmunroakusa** [comment]
Thank you so much! This is the official stable release? I've been working with beta well enough for a while now!...Damn. Yeah. Exciting news, will do that now.

**Comment by blairmunroakusa** [comment]
Or maybe we  were on just alpha? I dunno.

**Comment by HCastano** [comment]
Yep, this is the official stable release. You were roughly on one of the `beta` releases

**Comment by blairmunroakusa** [comment]
Done.
Note: Openbrush 3.0.0 contracts still uses `#![feature(min_specialization)]` thus nightly build with cargo contract v2.0.0 needed, unfortunately. I am dropping in on brushfam to see what their thoughts are.
