### ISSUE TITLE
Figure out how to capture entire event during e2e test

### ISSUE THREAD

**Issue by blairmunroakusa** [interlock-network/interlock-smartcontracts#225]
- Due to fact that openbrush invokes 'cross contract calls',
it is not possible to run standard unit tests for any functions
that include PSP22 standard messages, so we need to perform e2e tests in general.
- For now, the most we can do is verify within e2e tests that a
particular event occurred.
- There is no clear way or documented way to catch events in their entirety within an
e2e test (ie, the topics and values).
- To make up for this for the time being, in this non-e2e test we verify that *when* one of the
three events are emitted, their topics are indeed accurate in general.

We need to figure out how to scale decode the event.bytes() from the EventDetails struct.

**Comment by ganesh1233456** [comment]
hey @blairmunroakusa I am playing around with normal ink test decode events. I managed to decode event of `flip` method and test from `MyEvent` struct. You can [look this link](https://ink-playground.substrate.io/?id=2c4375ed1aac6919d309dea9f4a79d51) but I don't know whether is this what you are looking for. Can you pleas give me some feedback :)

**Comment by blairmunroakusa** [comment]
Hey @ganesh1233456 ! Thanks for the comment.

First, your decode approach to testing seems very nice, and I might yank that for my own unit event tests (the tests from the ink-examples psp22 contract are pretty gnarly).

The issue isn't quite what you did in the playground. Those event tests you wrote are good for any `#[ink::test]`. The events I am trying to test for are for `#[ink_e2e::test]`. For example, when you do
```
            // When
            let flip = build_message::<EventTestRef>(contract_account_id.clone())
                .call(|event_test| event_test.flip());
            let _flip_result = client
                .call(&ink_e2e::bob(), flip, 0, None)
                .await
                .expect("flip failed");
``` in your `#[e2e_ink::test]`, you won't be able to capture your `MyEvent` in the same way as you did it in your `#[ink::test]`. Does that make sense?

**Comment by blairmunroakusa** [comment]
From Brushfam Element:
![image](https://user-images.githubusercontent.com/69293813/222607950-69207813-c376-41a8-bc46-ffc5011d673e.png)
```rust
// Propose
    let propose_response = client
        .call(&ink_e2e::bob(), propose, 0, None)
        .await
        .unwrap();

    // Filter the events
    let contract_emitted_event = propose_response
        .events
        .iter()
        .find(|event| {
            event
                .as_ref()
                .expect("Expect Event")
                .event_metadata()
                .event()
                == "ContractEmitted"
        })
        .expect("Expect ContractEmitted event")
        .unwrap();

    // Decode to the expected event type (skip field_context)
    let event = contract_emitted_event.field_bytes();
    let decoded_event = <ProposalCreated as scale::Decode>::decode(&mut &event[35..])
        .expect("invalid data");

    // Destructor
    let ProposalCreated {
        proposer,
        proposal_id: prop_id,
        proposal: prop,
        start_block,
        end_block,
        description: des,
    } = decoded_event;

    // Assert with the expected value
    assert_eq!(proposer, bob);
    assert_eq!(prop_id, proposal_id);
    assert_eq!(prop, proposal);
    assert_eq!(start_block, 2);
    assert_eq!(end_block, 4);
    assert_eq!(des, description);
    ```
    
    Hey @ganesh1233456 ! Checkout above what I just picked up from Brushfam Element! ...I'm hoping this works...when I find the time to tinker with it I'll let you know (unless you beat me to it :) .

**Comment by ganesh1233456** [comment]
> From Brushfam Element: ![image](https://user-images.githubusercontent.com/69293813/222607950-69207813-c376-41a8-bc46-ffc5011d673e.png)
> 
> ```rust
> // Propose
>     let propose_response = client
>         .call(&ink_e2e::bob(), propose, 0, None)
>         .await
>         .unwrap();
> 
>     // Filter the events
>     let contract_emitted_event = propose_response
>         .events
>         .iter()
>         .find(|event| {
>             event
>                 .as_ref()
>                 .expect("Expect Event")
>                 .event_metadata()
>                 .event()
>                 == "ContractEmitted"
>         })
>         .expect("Expect ContractEmitted event")
>         .unwrap();
> 
>     // Decode to the expected event type (skip field_context)
>     let event = contract_emitted_event.field_bytes();
>     let decoded_event = <ProposalCreated as scale::Decode>::decode(&mut &event[35..])
>         .expect("invalid data");
> 
>     // Destructor
>     let ProposalCreated {
>         proposer,
>         proposal_id: prop_id,
>         proposal: prop,
>         start_block,
>         end_block,
>         description: des,
>     } = decoded_event;
> 
>     // Assert with the expected value
>     assert_eq!(proposer, bob);
>     assert_eq!(prop_id, proposal_id);
>     assert_eq!(prop, proposal);
>     assert_eq!(start_block, 2);
>     assert_eq!(end_block, 4);
>     assert_eq!(des, description);
> ```
> 
> Hey @ganesh1233456 ! Checkout above what I just picked up from Brushfam Element! ...I'm hoping this works...when I find the time to tinker with it I'll let you know (unless you beat me to it :) .

I just get your notification I will definitely try😁

**Comment by ganesh1233456** [comment]
[playground link](https://ink-playground.substrate.io/?id=f114b63cdbcb6321e98c5078b645986f)

decode event successful but on `assert_eq!(flip_value, 100)` doesn't pass. Even though I assign `flip_value: i32` in `MyEvent2` and input 100.

<img width="1439" alt="Screenshot 2023-03-03 at 09 06 49" src="https://user-images.githubusercontent.com/42571338/222623355-782f06bd-ad58-46fe-a80a-30115ae35aba.png">

<img width="1439" alt="Screenshot 2023-03-03 at 09 03 47" src="https://user-images.githubusercontent.com/42571338/222622922-25475e4a-af66-4c78-8ee4-9b07ef367d76.png">

and other things is when I change `flip_value: bool`, then decode event fails. 

<img width="1439" alt="Screenshot 2023-03-03 at 09 13 33" src="https://user-images.githubusercontent.com/42571338/222624268-158f0d41-fe60-48e6-8d4c-9862946218d4.png">

**Comment by alessandro-baldassarre** [comment]
hi @blairmunroakusa, i forked the repo and test what i sent you on Brush Element and it works! I wanted to create a PR but I realized that since you don't use a .rustfmt.toml my ide formatted everything by itself :) I'll leave you the commit so you can take a look. d2141ef23b6c016ba3dd90e2305a2ab33daac740

**Comment by blairmunroakusa** [comment]
Hey @alessandro-baldassarre ! Btw...glad you pointed me to that issue from Stack Exchange!

Yeah, my approach to readability and formatting is ...nonconventional?
I favor short line length, copious whitespace, and comment tabbing...
...but if everybody's formatting like how your IDE does it...I'm totally down :).
It is probably a professional shortcoming of mine that I don't use a .rustfmt.toml, but I am still learning things.
Thank you for applying yours. I do all my formatting by hand in vim. I guess it's pretty cringe hah.

I'll take the weekend to review these changes and get back to you. So far though, I am super stoked about your solution to this even emission problem.

@ganesh1233456 Yeah I see your results...I'll look into those over the weekend also and get back to you no?

Peace all.

**Comment by ganesh1233456** [comment]
> Hey @alessandro-baldassarre ! Btw...glad you pointed me to that issue from Stack Exchange!
> 
> Yeah, my approach to readability and formatting is ...nonconventional? I favor short line length, copious whitespace, and comment tabbing... ...but if everybody's formatting like how your IDE does it...I'm totally down :). It is probably a professional shortcoming of mine that I don't use a .rustfmt.toml, but I am still learning things. Thank you for applying yours. I do all my formatting by hand in vim. I guess it's pretty cringe hah.
> 
> I'll take the weekend to review these changes and get back to you. So far though, I am super stoked about your solution to this even emission problem.
> 
> @ganesh1233456 Yeah I see your results...I'll look into those over the weekend also and get back to you no?
> 
> Peace all.

thanks @blairmunroakusa I don't know why I am getting the issue even though I followed exactly same as recommended code.

**Comment by blairmunroakusa** [comment]
Hey @ganesh1233456 , so it looks like you are decoding for `event[1..]`. Try decoding `event[35..]` or `event[34..]`, whichever works.

**Comment by blairmunroakusa** [comment]
@alessandro-baldassarre 
So had some time to explore your solution. Results:
- Still need to filter for multiple events if >1 are present (see example below). I added an additional boolean test for the `.find` method on iterator. It's rather long, but it get's the job done.
- Also, I do not understand exactly what the first 35 bytes of the event field bytes array is, but for a couple cases, I was only able to decode the event for `&event[34..]` instead of `&event[..35]`. (This was for a custom event, and an event returning `None` as a topic field).

[Here's the commit.](https://github.com/interlock-network/interlock-smartcontracts/commit/d2a43872f8e9cdda38a060df7635708d8704dd6c)

Also, I am waiting to merge any formatting changes  until I merge a couple other things first.

```rust
            // bob transfers 1000 ILOCK from alice to charlie
            let bob_transfer_from_msg = build_message::<ILOCKmvpRef>(contract_acct_id.clone())
                .call(|contract| contract.transfer_from(
                    alice_account.clone(), charlie_account.clone(), 1000, Vec::new())
            );
            let transfer_from_response = client
                .call(&ink_e2e::bob(), bob_transfer_from_msg, 0, None).await.unwrap();
            
            // filter for approval event
            let contract_emitted_approval = transfer_from_response
                .events
                .iter()
                .find(|event| {
                    event
                        .as_ref()
                        .expect("expected event")
                        .event_metadata()
                        .event()
                        == "ContractEmitted" &&
                        String::from_utf8_lossy(
                            event.as_ref().expect("bad event").bytes()).to_string()
                       .contains("ILOCKmvp::Approval")
                })
                .expect("Expect ContractEmitted event")
                .unwrap();

            // decode to the expected event type (skip field_context)
            let approval_event = contract_emitted_approval.field_bytes();
            let decoded_approval =
                <Approval as scale::Decode>::decode(&mut &approval_event[35..]).expect("invalid data");

            // destructor decoded eapproval
            let Approval { owner, spender, amount } = decoded_approval;

            // assert with the expected value
            assert_eq!(owner, Some(alice_account), "encountered invalid Approval.owner");
            assert_eq!(spender, Some(bob_account), "encountered invalid Approval.spender");
            assert_eq!(amount, 1000 - 1000, "encountered invalid Approval.amount");  
            
            // filter for transfer event
            let contract_emitted_transfer = transfer_from_response
                .events
                .iter()
                .find(|event| {
                    event
                        .as_ref()
                        .expect("expected event")
                        .event_metadata()
                        .event()
                        == "ContractEmitted" &&
                        String::from_utf8_lossy(
                            event.as_ref().expect("bad event").bytes()).to_string()
                       .contains("ILOCKmvp::Transfer")
                })
                .expect("Expect ContractEmitted event")
                .unwrap();

            // decode to the expected event type (skip field_context)
            let transfer_event = contract_emitted_transfer.field_bytes();
            let decoded_transfer =
                <Transfer as scale::Decode>::decode(&mut &transfer_event[35..]).expect("invalid data");

            // destructor decoded transfer
            let Transfer { from, to, amount } = decoded_transfer;

            // assert with the expected value
            assert_eq!(from, Some(alice_account), "encountered invalid Transfer.from");
            assert_eq!(to, Some(charlie_account), "encountered invalid Transfer.to");
            assert_eq!(amount, 1000, "encountered invalid Transfer.amount");  
```

**Comment by alessandro-baldassarre** [comment]
@blairmunroakusa 
yes, if you have more than one event in a tx you need to filter to "extract" the right one.

for the number of bytes was just a quick fix to skip the context:

``` 
Struct Value {
    pub value: ValueDef<T>,
    pub context: T,  
```

but for sure is not the nice one :) , instead if you find a better solution let me know that I don't think I have time soon to look for other solutions.


however if you need the advancement of a block, in unit tests you can use ```ink::env::test::advance_block()```, while in e2e if you use substrate-contract-node it use the instant finality, next block at each call ( not dry run)

**Comment by ganesh1233456** [comment]
> Awesome @ganesh1233456 ! Glad you got it working. :) Yeah I had a hell of a time figuring that out. lol
> 
> Sounds like @alessandro-baldassarre has it dialed in though with the context. I just...don't know what the context is?
> 
> I am wondering...should we open issues with ink-examples or openbrush to share this solution for docs or perhaps solicit for refinement? Or should I create a branch of ink-examples and request a PR, for example? I am happy to do that, but I do not know the 'proper way' to go about sharing this sort of thing in the dev community...but I wish it existed as a reference implementation.
> 
> I for one have little time, but this seems worthy of sharing.
> 
> * Also, thank you for block-advance tidbit. My understanding is the easiest way to do this in contract node is to brute force for-loop a call.

@blairmunroakusa yes it is important one and needs to share this solution. May be one way to open PR in ink-example :)

**Comment by ganesh1233456** [comment]
@blairmunroakusa I have created repo for [testing-event-decode](https://github.com/ganesh1233456/ink-examples/tree/ink-e2e-decode-event/testing-event-decode) in ink-example. Does that make sense :)?

**Comment by blairmunroakusa** [comment]
@ganesh1233456 ..we'll see what @alessandro-baldassarre  thinks, but for now I would suggest calling it `e2etest_event_decode` ... what do you think?

**Comment by ganesh1233456** [comment]
@blairmunroakusa you mean folder name? [if so i changed here](https://github.com/ganesh1233456/ink-examples/tree/ink-e2e-decode-event/e2etest_event_decode)

**Comment by alessandro-baldassarre** [comment]
@ganesh1233456 @blairmunroakusa 

Sounds good for me, have a look at the PR @ganesh1233456 you mentioned me twice :)
